version: '3.8'

services:
  kedro-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./ml_models:/app/ml_models
      - ./data:/app/data
