version: '3.8'

services:
  kedro-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Mapowanie portu z kontenera na lokalny port 8000
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root_password
      - DATABASE_NAME=my_database
    volumes:
      - ./ml_models:/app/ml_models
      - ./data:/app/data

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
